name: graphs
version: 0.1.2
description: Graph algorithms operation an graphs in any representation.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/graphs

environment:
  sdk: '>=1.24.0 <2.0.0'

dev_dependencies:
  test: ^0.12.0
  # For examples
  analyzer: ^0.32.0
  path: ^1.1.0
