name: graphs
version: 0.1.3-dev
description: Graph algorithms operation an graphs in any representation.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/graphs

environment:
  sdk: '>=2.0.0-dev.64.0 <3.0.0'

dev_dependencies:
  test: ^0.12.0
  # For examples
  analyzer: ^0.32.0
  path: ^1.1.0
